### ISSUE TITLE
Menu is not accessible

### ISSUE THREAD

**Issue by milesmcc** [phillipian/phillipian-wp-2019#1]
Often, those with different accessibility needs use the keyboard to navigate websites. Quoting [WebAIM](https://webaim.org/techniques/keyboard/):

> Keyboard accessibility is one of the most important aspects of web accessibility. Many users with motor disabilities rely on a keyboard. Blind users also typically use a keyboard for navigation. Some people have tremors which don't allow for fine muscle control. Others have little or no use of their hands. Some people simply do not have hands, whether due to a birth defect, an accident, or amputation. In addition to traditional keyboards, some users may use modified keyboards or other hardware that mimics the functionality of a keyboard.

Given that "accessible navigation" is one of the top priorities for the site, the "sections" dropdown button should be navigable via keyboard. Currently, the button cannot be focused using the keyboard (at least on my browser, Chromium).

<small>The site looks great, though!</small>

**Comment by wwsalmon** [comment]
Thanks for the comment! [The navbar and search menu have been made keyboard-navigable](https://github.com/phillipian/phillipian-wp-2019/commit/db5d73fb578e592ae2a553b9fd6a42662c9ceebd).
