### ISSUE TITLE
Logo formatting error

### ISSUE THREAD

**Issue by InnovativeInventor** [phillipian/phillipian-wp-2019#2]
After scrolling, the logo moves down too much and is partially obscured. This appears on Chrome, Chromium, and Firefox and on all tested articles.

![image](https://user-images.githubusercontent.com/20117409/55295017-90441b00-53d6-11e9-940e-5818e5816335.png)

**Comment by wwsalmon** [comment]
The navbar and most of the old theme was replaced by the redesign so this is no longer a problem.
