### ISSUE TITLE
fix margins on homepage

### ISSUE THREAD

**Issue by steph-y-yang** [phillipian/phillipian-wp-2019#45]
maybe it's just my screen width, but none of the new features have margins (between them and the sides of the windows)

**Comment by wwsalmon** [comment]
What is the window width? Can you send a screenshot?

Are you sure you have the correct CSS loaded? Try hard refreshing to clear any old cached CSS. I can't reproduce this at any width on my end

**Comment by steph-y-yang** [comment]
caching issue
